<?php

namespace Rafflex\Nea\Services;

use Illuminate\Support\Facades\Config;
use Themosis\Support\Facades\Action;
use Themosis\Support\Facades\Filter;

class Head
{
    public function register()
    {
        if((Config::get('nea.global.wp-head.remove-emoji') == true)) {
            $this->removeEmojiFromHead();
        }

        if((Config::get('nea.global.wp-head.remove-feed-links') == true)) {
            $this->removeAutoGeneratedFeedLinks();
        }

        if((Config::get('nea.global.wp-head.remove-meta-tags') == true)) {
            $this->removeMetaTags();
        }
    }

    /**
     * Remove emoji scripts from head
     */
    public function removeEmojiFromHead()
    {
        Action::remove('wp_print_styles', 'print_emoji_styles');
        Action::remove('wp_head', 'print_emoji_detection_script', 7);
    }

    /**
     * Remove auto generated feed links
     */
    public function removeAutoGeneratedFeedLinks()
    {
        Action::add( 'after_setup_theme', function () {
            Action::remove('wp_head', 'feed_links_extra', 3);
            Action::remove('wp_head', 'feed_links', 2);
        });
        Filter::add('wp_resource_hints', function ($hints, $relation_type) {
            if ('dns-prefetch' === $relation_type) {
                return array_diff(wp_dependencies_unique_hosts(), $hints);
            }

            return $hints;
        }, 10, 2);
    }

    /**
     * Remove some meta tags from WordPress
     */
    public function removeMetaTags()
    {
        Action::remove('wp_head', 'wp_generator');
        Action::remove('wp_head', 'rsd_link');
        Action::remove('wp_head', 'wlwmanifest_link');
        Action::remove('wp_head', 'wp_shortlink_wp_head');
    }
}
